#!/usr/bin/env python
import sys
import os
import os.path
import numpy as np
import getopt
import skysurvey as ss
from skysurvey.footprint import rectangle
from skysurvey.utils import make_printf_string, as_tuple
import pyfits
import skysurvey.pool2 as pool2

def usage():
	print "Usage: %s --bounds=bounds --format=[fits|text] --output=[outputfile] --quiet <catalog> <query>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'b:f:o:q', ['bounds=', 'format=', 'output=', 'quiet'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) != 2:
	print "Error: Incorrect number of command line arguments."
	usage()
	exit(-1)

def T(*args):
	""" User friendly specification of time:
		T([a,b], [b, c], [d, e]) --> intervalset([a,b], [b, c], [d, e])
		T([a], [b]) --> intervalset([a], [b])
		T(a) or T([a])--> intervalset([a])

		but, the often used case of:

		T(a, b) --> intervalset[a, b]
	"""
	from skysurvey.intervalset import intervalset

	hastuple = sum([ isinstance(a, tuple) or isinstance(a, list) for a in args ]) != 0

	if len(args) != 2 or hastuple:
		return intervalset(*args)
	else:
		return intervalset(tuple(args))

foot = []
format = 'text'
output = 'output.fits'
progress_callback = None
for o, a in optlist:
	if o in ('-b', '--bounds'):
		foot.extend(eval('[' + a + ']'))
		#print foot; exit()
	if o in ('--format', '-f'):
		if a not in ['text', 'fits']: usage(); exit(-1);
		format = a
	if o in ('--output', '-o'):
		output = a
	if o in ('--quiet', '-q'):
		progress_callback = pool2.progress_pass
catname, query = args



######### Actual work

cat = ss.Catalog(catname)
if format == 'text':
	# Text output
	fmt = None
	##rprev = None
	for row in cat.iterate(query, foot, progress_callback=progress_callback):
		if fmt == None:
			fmt = make_printf_string(row)
			print '# ' + ' '.join(row.dtype.names)
		print fmt % as_tuple(row)
		##if rprev != None and rprev['ra'] == row['ra']:
		##	print fmt % as_tuple(row)
		##	print fmt % as_tuple(rprev)
		##rprev = row.copy()
else:
	# FITS output
	rows = cat.fetch(query, foot, progress_callback=progress_callback)

	if 'cksumok' in rows.dtype.names:
		# Do ./lsd-query --format=fits ps1 'vecmd5(hdr) == cksum as cksumok'
		assert rows['cksumok'].all()
		print "CHECKSUM OK"

	# workaround for pyfits bugs -- it doesn't know what to do with bool and uint?? columns
	#                               so for now just convert these to signed, and emit a warning
	#			     -- it also incorrectly stores i1 columns as False
	dtype = []
	copy = False
	for col in rows.dtype.names:
		t, o = rows.dtype.fields[col]
		conv = False
		if   t == np.bool:	t = 'i2'; conv = True; copy = True
		elif t == np.uint64:	t = 'i8'; conv = True
		elif t == np.uint32:	t = 'i4'; conv = True
		elif t == np.uint16:	t = 'i2'; conv = True
		dtype += [(col, t)]
		if conv:
			print >> sys.stderr, 'WARNING: Stored "%s" as a signed integer, as pyfits can\'t handle unsigned and/or bools.' % (col)
	rows = rows.as_ndarray()

	# pyfits bugs workarounds
	if copy:
		rows2 = np.empty(len(rows), dtype=dtype)
		for col in rows.dtype.names: rows2[col] = rows[col]
		rows = rows2
	else:
		rows = rows.view(dtype=dtype)

	if os.path.exists(output):
		os.unlink(output)
	pyfits.writeto(output, rows)

	print >> sys.stderr, 'Output in %s' % (output)
