#!/usr/bin/env python
#
# Example: lsd-import-smf -c ps1_det ps1_exp ./test.smf
#

import sys
import getopt
import skysurvey.smf as smf
import skysurvey as lsd
from   skysurvey.utils import *

def usage():
	print "Usage: %s [-c|--create] <det_cat_dir> <exp_cat_dir> <smf_file(s)>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'c', ['create'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) < 3:
	print "Error: Not enough command line arguments."
	usage()
	exit(-1)

(det_catdir, exp_catdir, files) = args[0], args[1], args[2:]

create = False
for (o, a) in optlist:
	if o == '-c' or o == '--create':
		create = True

#
# Actual work
#

print "Importing SMF files ",
smf.import_from_smf(det_catdir, exp_catdir, files, create)
print " done."

#cat = lsd.Catalog(cat_dir)
#print "Building neighbor cache ",
#cat.build_neighbor_cache()
#print " done."
#
#print "Computing summary statistics ",
#cat.compute_summary_stats()
#print " done."
