#!/usr/bin/env python
#
# Example: lsd-xmatch ps1_obj sdss
#

import sys
import getopt
import skysurvey.smf as smf
import skysurvey as lsd
from   skysurvey.utils import *

def usage():
	print "Usage: %s [--radius=<arcsec>] <from_cat> <to_cat>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'hr:', ['help', 'radius='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) != 2:
	print "Error: Incorrect number of command-line arguments."
	usage()
	exit(-1)

(from_cat_dir, to_cat_dir) = args[0], args[1]

radius = 1.
for (o, a) in optlist:
	if o == '-h' or o == '--help':
		usage()
		exit()
	if o == '-r' or o == '--radius':
		radius = float(a)

#
# Actual work
#

from_cat = lsd.Catalog(from_cat_dir)
to_cat   = lsd.Catalog(to_cat_dir)

lsd.xmatch(from_cat, to_cat, radius/3600.)
