#!/usr/bin/env python

import os, os.path, sys, glob

try:
        import numpy
except ImportError:
        raise Exception("LSD requires numpy")

from distutils.core import setup, Extension
from distutils.command.build_py import build_py as _build_py

class build_py(_build_py):
        """ An override for build_py that records the location
            where the package was installed into lsd.config
            module variables.
            
            It is only active in the 'install' phase.
        """
	def build_module (self, module, module_file, package):
		if package == 'lsd.config' and 'install' in self.distribution.command_obj:
			iobj = self.distribution.command_obj['install']
			outfile = self.get_module_outfile(self.build_lib, package.split('.'), module)
			dir = os.path.dirname(outfile)
			self.mkpath(dir)
			with file(outfile, 'w') as fp:
				import textwrap
				fp.write(textwrap.dedent(
				"""\
				# Do not edit. This file is regenerated by setup.py on install.
				data_dir = '{datadir}'
				bin_dir  = '{bindir}'
				""").format(datadir=os.path.join(iobj.install_data, 'share', 'lsd'), bindir=iobj.install_scripts))
			return (outfile, 1)
		else:
			return _build_py.build_module(self, module, module_file, package)

inc = [ numpy.get_include() ]

longdesc = """Large Survey Database"""

args = { 
	'cmdclass'		: { 'build_py' : build_py },
	'name'			: "lsd",
	'version'		: "0.5.4", # When you change this, modify __version__ in __init__.py
	'description'	 	: "Large Survey Database Python Module",
	'long_description'	: longdesc,
	'license'		: "GPLv2",
	'author'		: "Mario Juric",
	'author_email'		: "mjuric@cfa.harvard.edu",
	'maintainer'		: "Mario Juric",
	'maintainer_email'	: "mjuric@cfa.harvard.edu",
	'url'			: "http://mwscience.net/lsd",
	'download_url'		: "http://mwscience.net/lsd/download",
	'classifiers'		: [
					'Development Status :: 3 - Alpha',
					'Intended Audience :: Science/Research', 
					'Intended Audience :: Developers',
					'License :: OSI Approved :: GNU General Public License (GPL)', 
					'Programming Language :: C++', 
					'Programming Language :: Python :: 2', 
					'Programming Language :: Python :: 2.7',
					'Operating System :: POSIX :: Linux',
					'Topic :: Database',
					'Topic :: Scientific/Engineering :: Astronomy'
	],
	'scripts'	: ['src/lsd-footprint', 'src/lsd-import-sdss', 'src/lsd-make-object-catalog',
	 			'src/lsd-import-dvo', 'src/lsd-import-smf',
	 			'src/lsd-query', 'src/lsd-xmatch', 'src/mr-peer',
	 			'src/lsd-manager', 'src/lsd-admin', 'src/lsd-import',
	 			'src/lsd-check'],
	'packages'	: ['lsd', 'lsd.builtins', 'lsd.importers', 'surveys', 'surveys.ps1', 'mr', 'lsd.config'],
	'package_dir'	: {'': 'src'},
	'ext_modules'	: [Extension('lsd.native', ['src/native/main.cpp'], include_dirs=inc)],
	'data_files'    : [
				('share/lsd/examples', ['src/examples/latitude_histogram.py', 'src/examples/count_rows.py']),
				('share/lsd/schemas', glob.glob('src/schemas/*.yaml') + glob.glob('src/schemas/*.map')),
				('share/lsd/sfd-dust-maps', ['src/data/sfd-dust-maps/SFD_dust_4096_ngp.fits.gz', 'src/data/sfd-dust-maps/SFD_dust_4096_sgp.fits.gz'])
			]
}

setup(**args)
