#!/usr/bin/env python
#
# Example: lsd-check object-table
#

import sys
import getopt
import lsd
import lsd.smf as smf
from lsd.utils import *
from lsd.tui import *

def usage():
	print "Usage: %s [--explist=<explist.txt>] [--radius=<arcsec>] <obj_table> <det_table>" % sys.argv[0]

optlist, (dbdir,), (obj_tabname, det_tabname) = tui_getopt('e:r:', ['explist=', 'radius='], 2, usage)

radius = 1.
explist = None
for (o, a) in optlist:
	if o == '-r' or o == '--radius':
		radius = float(a)
	elif o == '-e' or o == '--explist':
		explist = np.loadtxt(a, dtype=np.uint64)

#
# Actual work
#

db = lsd.DB(dbdir)

smf.sanity_check_object_table(db, obj_tabname, det_tabname, radius/3600., explist)
print "Database OK."
