#!/usr/bin/env python
#
# Example: lsd-import-sdss -c sdss /raid14/sweeps/sdss3/2009-11-16.v2/301
#

import sys
import getopt
import lsd
import lsd.sdss  as sdss
from   lsd.utils import *

def usage():
	print "Usage: %s [-c|--create] <db> <sdss_table> <sweep_file_dir>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'c', ['create'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) != 3:
	print "Error: Not enough command line arguments."
	usage()
	exit(-1)

create = False
for (o, a) in optlist:
	if o == '-c' or o == '--create':
		create = True

dbdir, tabname, sweep_dir = args

db = lsd.DB(dbdir)

#
# Actual work
#
files = shell('find "' + sweep_dir + '" -name "*star*.fits.gz" -o -name "*gal*.fits.gz" ').splitlines()

print "Importing SDSS catalog:"
sdss.import_from_sweeps(db, tabname, files, create)
print " done."

print "Building neighbor cache ",
db.build_neighbor_cache(tabname)
print " done."

print "Computing summary statistics ",
db.compute_summary_stats(tabname)
print " done."
print "Total number of objects in catalog: ", db.table(tabname).nrows()
