#!/usr/bin/env python
#
# Example: lsd-xmatch ps1_obj sdss
#

import sys
import getopt
import skysurvey.smf as smf
import skysurvey as lsd
from   skysurvey.utils import *

def usage():
	print "Usage: %s [--radius=<arcsec>] <db> <from_cat> <to_cat>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'hr:', ['help', 'radius='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) != 3:
	print "Error: Incorrect number of command-line arguments."
	usage()
	exit(-1)

(dbdir, from_cat_dir, to_cat_dir) = args
db = lsd.DB(dbdir)

radius = 1.
for (o, a) in optlist:
	if o == '-h' or o == '--help':
		usage()
		exit()
	if o == '-r' or o == '--radius':
		radius = float(a)

#
# Actual work
#

lsd.xmatch(db, from_cat_dir, to_cat_dir, radius/3600.)
