#!/usr/bin/env python
#
# Example: lsd-import-sdss -c sdss /raid14/sweeps/sdss3/2009-11-16.v2/301
#

import sys
import getopt
import lsd
import lsd.sdss  as sdss
from lsd.utils import *
from lsd.tui import *

def usage():
	print "Usage: %s [-c|--create] <sdss_table> <sweep_file_dir>" % sys.argv[0]

optlist, (dbdir,), (tabname, sweep_dir) = tui_getopt('ca', ['create', 'all'], 2, usage)

create = False
all = False
for (o, a) in optlist:
	if o == '-c' or o == '--create':
		create = True
	if o == '-a' or o == '--all':
		all = True

#
# Actual work
#
db = lsd.DB(dbdir)

files = shell('find "' + sweep_dir + '" -name "*star*.fits.gz" -o -name "*gal*.fits.gz" ').splitlines()

print "Importing SDSS catalog:"
sdss.import_from_sweeps(db, tabname, files, create, all)
print " done."

print "Building neighbor cache ",
db.build_neighbor_cache(tabname)
print " done."

print "Computing summary statistics ",
db.compute_summary_stats(tabname)
print " done."
print "Total number of objects in catalog: ", db.table(tabname).nrows()
