#!/usr/bin/env python
#
# Example: lsd-import-smf -c ps1_det ps1_exp ./test.smf
#

import sys
import getopt
import lsd.smf as smf
from   lsd.utils import *

def usage():
	print "Usage: %s [-c|--create] <db> <obj_cat_dir> <det_cat_dir>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'c', ['create'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) != 3:
	print "Error: Not enough command line arguments."
	usage()
	exit(-1)

(dbdir, obj_catdir, det_catdir) = args

create = False
for (o, a) in optlist:
	if o == '-c' or o == '--create':
		create = True

#
# Actual work
#

db = lsd.DB(dbdir)
smf.make_object_catalog(db, obj_catdir, det_catdir, create=create)
