#!/usr/bin/env python
#
# Example: lsd-import-smf -c ps1_det ps1_exp ./test.smf
#

import sys
import getopt
import lsd
import lsd.smf as smf
from lsd.utils import *
from lsd.tui import *

def usage():
	print "Usage: %s [-c|--create] <obj_table> <det_table>" % sys.argv[0]

optlist, (dbdir,), (obj_tabname, det_tabname) = tui_getopt('c', ['create'], 2, usage)

create = False
for (o, a) in optlist:
	if o == '-c' or o == '--create':
		create = True

#
# Actual work
#

db = lsd.DB(dbdir)
smf.make_object_catalog(db, obj_tabname, det_tabname, create=create)
