#!/usr/bin/env python
#
# Example: lsd-xmatch ps1_obj sdss
#

import sys
import getopt
import lsd
from   lsd.utils import *

def usage():
	print "Usage: %s [--radius=<arcsec>] <db> <from_table> <to_table>" % sys.argv[0]

try:
	optlist, args = getopt.getopt(sys.argv[1:], 'hr:', ['help', 'radius='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	exit(-1)

if len(args) != 3:
	print "Error: Incorrect number of command-line arguments."
	usage()
	exit(-1)

radius = 1.
for (o, a) in optlist:
	if o == '-h' or o == '--help':
		usage()
		exit()
	if o == '-r' or o == '--radius':
		radius = float(a)

(dbdir, from_tabname, to_tabname) = args

#
# Actual work
#

db = lsd.DB(dbdir)
lsd.xmatch(db, from_tabname, to_tabname, radius/3600.)
